development:
  # must specify url in .env file
  url: {{envOr "DATABASE_URL" ""}}

test:
  dialect: "mysql"
  host: "db_test"
  port: "3306"
  # database: {{envOr "DB_NAME_TEST" "test"}}
  # user: {{envOr "DB_USER_TEST" "root"}}
  # password: {{envOr "DB_PASSWORD_TEST" "secret"}}
  database: "brokernode_test"
  user: "root"
  password: "secret"

production:
  # must specify url in .env file
  url: {{envOr "DATABASE_URL" ""}}
